specfile_path: freecad.spec
upstream_project_url: https://github.com/FreeCAD/FreeCAD
files_to_sync:
    - .packit.yaml
    - freecad.spec
    - package/scripts/write_version_info.py
issue_repository: https://github.com/filippor/FreeCAD-fedora-packaging
actions:
  #post-upstream-clone:
    #- bash -c '/usr/bin/python3 package/scripts/write_version_info.py freecad_version.txt'
    #- rm -f freecad-sources.tar.gz
  changelog-entry:
    - bash -c 'git log --no-merges --pretty="format:- %s (%an)" $(git describe --tags --abbrev=0 )..HEAD -- |sed 's/%/%%/g''
  create-archive:
    - git submodule update --init
    - bash -c 'git ls-files --recurse-submodules | tar  -caf freecad-sources.tar.gz -T-'
    - echo -n 'freecad-sources.tar.gz'
downstream_package_name: freecad
additional_packages:
    - python3

jobs:
  - job: pull_from_upstream
    trigger: release
    dist_git_branches:
      - fedora-all
